var DEFAULT_SCALE = 1;

// bonus parameters
var BONUS_DURATION = 5000,
    BONUS_SCALE = 0.25,
    BONUS_OPACITY = 0.5,
    BONUS_SPEED = 250,
    BONUS_ITEM_MIN_SCALE = 0.3,
    SCALE_STEP = 0.03;

//player parameters
var PLAYER_DEFAULT_OPACITY = 1,
    PLAYER_DEFAULT_SPEED = 180;

//bonus item time to appear
var BONUS_ITEM_TIME_APPEARED_MIN = 3000,
    BONUS_ITEM_TIME_APPEARED_MAX = 10000;

//bonus item drawing period
var BONUS_ITEM_DURATION_TIME_MIN = 2000,
    BONUS_ITEM_DURATION_TIME_MAX = 5000;

//entity radius
var ENTITY_RADIUS_MIN = 10,
    ENTITY_RADIUS_MAX = 50;

// entity attacking direction interval
var RANDOM_ATTACK_ENTITY_INTERVAL_MIN = 200,
    PLAYER_ATTACK_ENTITY_INTERVAL_MIN = 0,
    ENTITY_INTERVAL_MAX = 2500;

// entity color
var RANDOM_ATTACK_ENTITY_COLOR = 'rgb(200,0,200)',
    PLAYER_ATTACK_ENTITY_COLOR = 'rgb(0,200,0)';

